dist: bionic

matrix:
  include:
    - language: python
      python:
        - "3.7"
      cache:
        pip
      install:
        - pip install -r server/requirements.txt
      script:
        - pytest -p no:warnings
    - language: node_js
      node_js:
        - 11
      cache:
        npm
      before_install:
        - cd client
      install:
        - npm install
      script:
        - npm test

notifications:
  email: false