version: "3.7"

services:
  backend:
    build: ./server
    image: myuri_backend
    container_name: myuri_backend
    environment:
    - FLASK_ENV=production
    - DATA_FOLDER=./data
    volumes: 
    - data:/srv/data
    restart: on-failure

  frontend:
    build: ./client
    image: myuri_frontend
    container_name: myuri_frontend_build
    volumes:
    - static:/app/dist

  nginx:
    image: nginx:1.17
    container_name: myuri_nginx
    volumes:
    - static:/var/www/html
    - data:/srv
    - ./config/nginx_dev/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
    - backend
    - frontend
    ports:
    - 80:80

volumes:
  data:
  static:
