version: "3.7"

services:
  postgres:
    image: postgres:13.1-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=myuri
      - POSTGRES_DB=myuri
      - PGDATA=/var/lib/postgresql/data/pgdata

  backend:
    build: ./app
    image: myuri_backend
    container_name: myuri_backend
    env_file:
      - .env
    environment:
      - DEBUG=true
      - POSTGRES_NAME=myuri
      - POSTGRES_USER=myuri
      - POSTGRES_HOST=postgres
    volumes:
      - ./data:/srv/data
      - ./app:/code
    ports:
    - 8000:8000
    depends_on:
      - postgres