version: "3"

services:
  backend:
    build: ./app
    image: myuri_backend
    container_name: myuri_backend
    env_file:
      - .env
    environment:
      - DEBUG=true
      - DATABASE_NAME=/srv/data/db.sqlite
    volumes:
      - ./data:/srv/data
      - ./app:/code
    ports:
      - 8000:8000