# Generated by Django 3.1.3 on 2020-12-21 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('chapter_id', models.CharField(max_length=32)),
                ('page_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('chapter_id',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='myuri.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('comic_type', models.IntegerField(choices=[(0, 'Other'), (1, 'Manga'), (2, 'Manwha'), (3, 'Manhua'), (4, 'Western')], default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('reading_order', models.IntegerField(choices=[(0, 'Right to Left'), (1, 'Left to Right'), (2, 'Vertical')], default=0)),
                ('artists', models.ManyToManyField(blank=True, to='myuri.Artist')),
                ('authors', models.ManyToManyField(blank=True, to='myuri.Author')),
                ('tags', models.ManyToManyField(blank=True, to='myuri.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='myuri.comic'),
        ),
    ]
