name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:

  # Push image to Dockerhub
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Build client
        run: |
          # Enter client
          cd client

          # Build client
          npm install
          npm run build

          # Return
          cd ..

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: ${{ github.repository_owner }}/myuri:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
